package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * HostProperties generated by hbm2java
 */
public class HostProperties  implements java.io.Serializable {
     private Integer hostPropertiesId = 0;
     private Integer lastUnauthenticatedResults;
     private String credentialedScan;
     private String policyUsed;
     private Integer patchSummaryTotalCves;
     private String cpe;
     private String os;
     private String cpe1;
     private String cpe0;
     private String systemType;
     private String operatingSystem;
     private String tracerouteHop10;
     private String tracerouteHop9;
     private String tracerouteHop8;
     private String tracerouteHop7;
     private String tracerouteHop6;
     private String tracerouteHop5;
     private String tracerouteHop4;
     private String tracerouteHop3;
     private String tracerouteHop2;
     private String tracerouteHop1;
     private String tracerouteHop0;
     private String hostEnd;
     private String hostIp;
     private String hostStart;
     private Integer reportHostId;

    public HostProperties() {
    }

	
    public HostProperties(Integer hostPropertiesId) {
        this.hostPropertiesId = hostPropertiesId;
    }
    public HostProperties(Integer hostPropertiesId, Integer lastUnauthenticatedResults, String credentialedScan, String policyUsed, Integer patchSummaryTotalCves, String cpe, String os, String cpe1, String cpe0, String systemType, String operatingSystem, String tracerouteHop10, String tracerouteHop9, String tracerouteHop8, String tracerouteHop7, String tracerouteHop6, String tracerouteHop5, String tracerouteHop4, String tracerouteHop3, String tracerouteHop2, String tracerouteHop1, String tracerouteHop0, String hostEnd, String hostIp, String hostStart, Integer reportHostId) {
       this.hostPropertiesId = hostPropertiesId;
       this.lastUnauthenticatedResults = lastUnauthenticatedResults;
       this.credentialedScan = credentialedScan;
       this.policyUsed = policyUsed;
       this.patchSummaryTotalCves = patchSummaryTotalCves;
       this.cpe = cpe;
       this.os = os;
       this.cpe1 = cpe1;
       this.cpe0 = cpe0;
       this.systemType = systemType;
       this.operatingSystem = operatingSystem;
       this.tracerouteHop10 = tracerouteHop10;
       this.tracerouteHop9 = tracerouteHop9;
       this.tracerouteHop8 = tracerouteHop8;
       this.tracerouteHop7 = tracerouteHop7;
       this.tracerouteHop6 = tracerouteHop6;
       this.tracerouteHop5 = tracerouteHop5;
       this.tracerouteHop4 = tracerouteHop4;
       this.tracerouteHop3 = tracerouteHop3;
       this.tracerouteHop2 = tracerouteHop2;
       this.tracerouteHop1 = tracerouteHop1;
       this.tracerouteHop0 = tracerouteHop0;
       this.hostEnd = hostEnd;
       this.hostIp = hostIp;
       this.hostStart = hostStart;
       this.reportHostId = reportHostId;
    }
   
    public Integer getHostPropertiesId() {
        return this.hostPropertiesId;
    }
    
    public void setHostPropertiesId(Integer hostPropertiesId) {
        this.hostPropertiesId = hostPropertiesId;
    }
    public Integer getLastUnauthenticatedResults() {
        return this.lastUnauthenticatedResults;
    }
    
    public void setLastUnauthenticatedResults(Integer lastUnauthenticatedResults) {
        this.lastUnauthenticatedResults = lastUnauthenticatedResults;
    }
    public String getCredentialedScan() {
        return this.credentialedScan;
    }
    
    public void setCredentialedScan(String credentialedScan) {
        this.credentialedScan = credentialedScan;
    }
    public String getPolicyUsed() {
        return this.policyUsed;
    }
    
    public void setPolicyUsed(String policyUsed) {
        this.policyUsed = policyUsed;
    }
    public Integer getPatchSummaryTotalCves() {
        return this.patchSummaryTotalCves;
    }
    
    public void setPatchSummaryTotalCves(Integer patchSummaryTotalCves) {
        this.patchSummaryTotalCves = patchSummaryTotalCves;
    }
    public String getCpe() {
        return this.cpe;
    }
    
    public void setCpe(String cpe) {
        this.cpe = cpe;
    }
    public String getOs() {
        return this.os;
    }
    
    public void setOs(String os) {
        this.os = os;
    }
    public String getCpe1() {
        return this.cpe1;
    }
    
    public void setCpe1(String cpe1) {
        this.cpe1 = cpe1;
    }
    public String getCpe0() {
        return this.cpe0;
    }
    
    public void setCpe0(String cpe0) {
        this.cpe0 = cpe0;
    }
    public String getSystemType() {
        return this.systemType;
    }
    
    public void setSystemType(String systemType) {
        this.systemType = systemType;
    }
    public String getOperatingSystem() {
        return this.operatingSystem;
    }
    
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }
    public String getTracerouteHop10() {
        return this.tracerouteHop10;
    }
    
    public void setTracerouteHop10(String tracerouteHop10) {
        this.tracerouteHop10 = tracerouteHop10;
    }
    public String getTracerouteHop9() {
        return this.tracerouteHop9;
    }
    
    public void setTracerouteHop9(String tracerouteHop9) {
        this.tracerouteHop9 = tracerouteHop9;
    }
    public String getTracerouteHop8() {
        return this.tracerouteHop8;
    }
    
    public void setTracerouteHop8(String tracerouteHop8) {
        this.tracerouteHop8 = tracerouteHop8;
    }
    public String getTracerouteHop7() {
        return this.tracerouteHop7;
    }
    
    public void setTracerouteHop7(String tracerouteHop7) {
        this.tracerouteHop7 = tracerouteHop7;
    }
    public String getTracerouteHop6() {
        return this.tracerouteHop6;
    }
    
    public void setTracerouteHop6(String tracerouteHop6) {
        this.tracerouteHop6 = tracerouteHop6;
    }
    public String getTracerouteHop5() {
        return this.tracerouteHop5;
    }
    
    public void setTracerouteHop5(String tracerouteHop5) {
        this.tracerouteHop5 = tracerouteHop5;
    }
    public String getTracerouteHop4() {
        return this.tracerouteHop4;
    }
    
    public void setTracerouteHop4(String tracerouteHop4) {
        this.tracerouteHop4 = tracerouteHop4;
    }
    public String getTracerouteHop3() {
        return this.tracerouteHop3;
    }
    
    public void setTracerouteHop3(String tracerouteHop3) {
        this.tracerouteHop3 = tracerouteHop3;
    }
    public String getTracerouteHop2() {
        return this.tracerouteHop2;
    }
    
    public void setTracerouteHop2(String tracerouteHop2) {
        this.tracerouteHop2 = tracerouteHop2;
    }
    public String getTracerouteHop1() {
        return this.tracerouteHop1;
    }
    
    public void setTracerouteHop1(String tracerouteHop1) {
        this.tracerouteHop1 = tracerouteHop1;
    }
    public String getTracerouteHop0() {
        return this.tracerouteHop0;
    }
    
    public void setTracerouteHop0(String tracerouteHop0) {
        this.tracerouteHop0 = tracerouteHop0;
    }
    public String getHostEnd() {
        return this.hostEnd;
    }
    
    public void setHostEnd(String hostEnd) {
        this.hostEnd = hostEnd;
    }
    public String getHostIp() {
        return this.hostIp;
    }
    
    public void setHostIp(String hostIp) {
        this.hostIp = hostIp;
    }
    public String getHostStart() {
        return this.hostStart;
    }
    
    public void setHostStart(String hostStart) {
        this.hostStart = hostStart;
    }
    public Integer getReportHostId() {
        return this.reportHostId;
    }
    
    public void setReportHostId(Integer reportHostId) {
        this.reportHostId = reportHostId;
    }




}


