package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * LoadCycle generated by hbm2java
 */
public class LoadCycle  implements java.io.Serializable {


     private int loadCycleId = 0;
     private Integer orgId;
     private String loadTime;
     private String loadBy;

    public LoadCycle() {
    }

	
    public LoadCycle(int loadCycleId) {
        this.loadCycleId = loadCycleId;
    }
    public LoadCycle(int loadCycleId, Integer orgId, String loadTime, String loadBy) {
       this.loadCycleId = loadCycleId;
       this.orgId = orgId;
       this.loadTime = loadTime;
       this.loadBy = loadBy;
    }
   
    public int getLoadCycleId() {
        return this.loadCycleId;
    }
    
    public void setLoadCycleId(int loadCycleId) {
        this.loadCycleId = loadCycleId;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    public String getLoadTime() {
        return this.loadTime;
    }
    
    public void setLoadTime(String loadTime) {
        this.loadTime = loadTime;
    }
    public String getLoadBy() {
        return this.loadBy;
    }
    
    public void setLoadBy(String loadBy) {
        this.loadBy = loadBy;
    }




}


