package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * Organization generated by hbm2java
 */
public class Organization  implements java.io.Serializable {


     private int orgId = 0;
     private String orgName;
     private String description;

    public Organization() {
    }

	
    public Organization(int orgId, String orgName) {
        this.orgId = orgId;
        this.orgName = orgName;
    }
    public Organization(int orgId, String orgName, String description) {
       this.orgId = orgId;
       this.orgName = orgName;
       this.description = description;
    }
   
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


