package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * PluginsPreference generated by hbm2java
 */
public class PluginsPreference  implements java.io.Serializable {


     private int pluginsPreferenceId = 0;
     private String pluginName;
     private String pluginId;
     private String preferenceName;
     private String preferenceType;
     private String preferenceValue;
     private String selectedValue;
     private Integer preferenceId;
     private String fullName;

    public PluginsPreference() {
    }

	
    public PluginsPreference(int pluginsPreferenceId) {
        this.pluginsPreferenceId = pluginsPreferenceId;
    }
    public PluginsPreference(int pluginsPreferenceId, String pluginName, String pluginId, String preferenceName, String preferenceType, String preferenceValue, String selectedValue, Integer preferenceId, String fullName) {
       this.pluginsPreferenceId = pluginsPreferenceId;
       this.pluginName = pluginName;
       this.pluginId = pluginId;
       this.preferenceName = preferenceName;
       this.preferenceType = preferenceType;
       this.preferenceValue = preferenceValue;
       this.selectedValue = selectedValue;
       this.preferenceId = preferenceId;
       this.fullName = fullName;
    }
   
    public int getPluginsPreferenceId() {
        return this.pluginsPreferenceId;
    }
    
    public void setPluginsPreferenceId(int pluginsPreferenceId) {
        this.pluginsPreferenceId = pluginsPreferenceId;
    }
    public String getPluginName() {
        return this.pluginName;
    }
    
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName;
    }
    public String getPluginId() {
        return this.pluginId;
    }
    
    public void setPluginId(String pluginId) {
        this.pluginId = pluginId;
    }
    public String getPreferenceName() {
        return this.preferenceName;
    }
    
    public void setPreferenceName(String preferenceName) {
        this.preferenceName = preferenceName;
    }
    public String getPreferenceType() {
        return this.preferenceType;
    }
    
    public void setPreferenceType(String preferenceType) {
        this.preferenceType = preferenceType;
    }
    public String getPreferenceValue() {
        return this.preferenceValue;
    }
    
    public void setPreferenceValue(String preferenceValue) {
        this.preferenceValue = preferenceValue;
    }
    public String getSelectedValue() {
        return this.selectedValue;
    }
    
    public void setSelectedValue(String selectedValue) {
        this.selectedValue = selectedValue;
    }
    public Integer getPreferenceId() {
        return this.preferenceId;
    }
    
    public void setPreferenceId(Integer preferenceId) {
        this.preferenceId = preferenceId;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }




}


