package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * Policy generated by hbm2java
 */
public class Policy  implements java.io.Serializable {


     private int policyId = 0;
     private String policyName;
     private Integer loadCycleId;

    public Policy() {
    }

	
    public Policy(int policyId) {
        this.policyId = policyId;
    }
    public Policy(int policyId, String policyName, Integer loadCycleId) {
       this.policyId = policyId;
       this.policyName = policyName;
       this.loadCycleId = loadCycleId;
    }
   
    public int getPolicyId() {
        return this.policyId;
    }
    
    public void setPolicyId(int policyId) {
        this.policyId = policyId;
    }
    public String getPolicyName() {
        return this.policyName;
    }
    
    public void setPolicyName(String policyName) {
        this.policyName = policyName;
    }
    public Integer getLoadCycleId() {
        return this.loadCycleId;
    }
    
    public void setLoadCycleId(Integer loadCycleId) {
        this.loadCycleId = loadCycleId;
    }




}


