package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * Preference generated by hbm2java
 */
public class Preference  implements java.io.Serializable {


     private Integer preferenceId = 0;
     private Integer policyId;

    public Preference() {
    }

	
    public Preference(Integer preferenceId) {
        this.preferenceId = preferenceId;
    }
    public Preference(Integer preferenceId, Integer policyId) {
       this.preferenceId = preferenceId;
       this.policyId = policyId;
    }
   
    public Integer getPreferenceId() {
        return this.preferenceId;
    }
    
    public void setPreferenceId(Integer preferenceId) {
        this.preferenceId = preferenceId;
    }
    public Integer getPolicyId() {
        return this.policyId;
    }
    
    public void setPolicyId(Integer policyId) {
        this.policyId = policyId;
    }




}


