package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * ReportItem generated by hbm2java
 */
public class ReportItem  implements java.io.Serializable {


     private Integer reportItemId = 0;
     private String name;
     private String value;
     private String text;
     private Integer reportHostId;
     
    public ReportItem() {
    }

	
    public ReportItem(Integer reportItemId) {
        this.reportItemId = reportItemId;
    }
    public ReportItem(Integer reportItemId, String name, String value, String text, Integer reportItemArtributeId) {
       this.reportItemId = reportItemId;
       this.name = name;
       this.value = value;
       this.text = text;
       this.reportHostId = reportItemArtributeId;
    }
   
    public Integer getReportItemId() {
        return this.reportItemId;
    }
    
    public void setReportItemId(Integer reportItemId) {
        this.reportItemId = reportItemId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    public Integer getReportHostId() {
        return reportHostId;
    }

    public void setReportHostId(Integer reportHostId) {
        this.reportHostId = reportHostId;
    }
   
    


}


