package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * ReportItemAttribute generated by hbm2java
 */
public class ReportItemAttribute  implements java.io.Serializable {


     private Integer reportItemId = 0;
     private Integer port;
     private String svcName;
     private String protocol;
     private Integer severity;
     private Integer pluginId;
     private String pluginName;
     private String pluginFamily;
     private Integer reportHostId;

    public ReportItemAttribute() {
    }

	
    public ReportItemAttribute(Integer reportItemId) {
        this.reportItemId = reportItemId;
    }
    public ReportItemAttribute(Integer reportItemId, Integer port, String svcName, String protocol, Integer severity, Integer pluginId, String pluginName, String pluginFamily) {
       this.reportItemId = reportItemId;
       this.port = port;
       this.svcName = svcName;
       this.protocol = protocol;
       this.severity = severity;
       this.pluginId = pluginId;
       this.pluginName = pluginName;
       this.pluginFamily = pluginFamily;
    }
   
    public Integer getReportItemId() {
        return this.reportItemId;
    }
    
    public void setReportItemId(Integer reportItemId) {
        this.reportItemId = reportItemId;
    }
    public Integer getPort() {
        return this.port;
    }
    
    public void setPort(Integer port) {
        this.port = port;
    }
    public String getSvcName() {
        return this.svcName;
    }
    
    public void setSvcName(String svcName) {
        this.svcName = svcName;
    }
    public String getProtocol() {
        return this.protocol;
    }
    
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }
    public Integer getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(Integer severity) {
        this.severity = severity;
    }
    public Integer getPluginId() {
        return this.pluginId;
    }
    
    public void setPluginId(Integer pluginId) {
        this.pluginId = pluginId;
    }
    public String getPluginName() {
        return this.pluginName;
    }
    
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName;
    }
    public String getPluginFamily() {
        return this.pluginFamily;
    }
    
    public void setPluginFamily(String pluginFamily) {
        this.pluginFamily = pluginFamily;
    }

    public Integer getReportHostId() {
        return reportHostId;
    }

    public void setReportHostId(Integer reportHostId) {
        this.reportHostId = reportHostId;
    }




}


