package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private Integer reportId = 0;
     private Integer loadCycleId;
     private String reportName;
     private String xmlnsCm;

    public Report() {
    }

	
    public Report(Integer reportId) {
        this.reportId = reportId;
    }
    public Report(Integer reportId, Integer loadCycleId, String reportName, String xmlnsCm) {
       this.reportId = reportId;
       this.loadCycleId = loadCycleId;
       this.reportName = reportName;
       this.xmlnsCm = xmlnsCm;
    }
   
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }
    public Integer getLoadCycleId() {
        return this.loadCycleId;
    }
    
    public void setLoadCycleId(Integer loadCycleId) {
        this.loadCycleId = loadCycleId;
    }
    public String getReportName() {
        return this.reportName;
    }
    
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }
    public String getXmlnsCm() {
        return this.xmlnsCm;
    }
    
    public void setXmlnsCm(String xmlnsCm) {
        this.xmlnsCm = xmlnsCm;
    }




}


