package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * ReportHost generated by hbm2java
 */
public class ReportHost  implements java.io.Serializable {


     private Integer reportHostId = 0;
     private String reportHostName;
     private Integer reportId;

    public ReportHost() {
    }

	
    public ReportHost(Integer reportHostId) {
        this.reportHostId = reportHostId;
    }
    public ReportHost(Integer reportHostId, String reportHostName, Integer reportId) {
       this.reportHostId = reportHostId;
       this.reportHostName = reportHostName;
       this.reportId = reportId;
    }
   
    public Integer getReportHostId() {
        return this.reportHostId;
    }
    
    public void setReportHostId(Integer reportHostId) {
        this.reportHostId = reportHostId;
    }
    public String getReportHostName() {
        return this.reportHostName;
    }
    
    public void setReportHostName(String reportHostName) {
        this.reportHostName = reportHostName;
    }
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }




}


