package entity;
// Generated Sep 12, 2016 10:48:21 PM by Hibernate Tools 4.3.1



/**
 * ServerPreference generated by hbm2java
 */
public class ServerPreference  implements java.io.Serializable {
     private int serverPreferenceId = 0;
     private String name;
     private String value;
     private Integer preferenceId;

    public ServerPreference() {
    }
	
    public ServerPreference(int serverPreferenceId) {
        this.serverPreferenceId = serverPreferenceId;
    }
    public ServerPreference(int serverPreferenceId, String name, String value, Integer preferenceId) {
       this.serverPreferenceId = serverPreferenceId;
       this.name = name;
       this.value = value;
       this.preferenceId = preferenceId;
    }
   
    public int getServerPreferenceId() {
        return this.serverPreferenceId;
    }
    
    public void setServerPreferenceId(int serverPreferenceId) {
        this.serverPreferenceId = serverPreferenceId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Integer getPreferenceId() {
        return this.preferenceId;
    }
    
    public void setPreferenceId(Integer preferenceId) {
        this.preferenceId = preferenceId;
    }




}


