DROP TABLE NESSUS_STRUCTURE;
DROP TABLE USERS;
DROP TABLE ORGANIZATION;
DROP TABLE LOAD_CYCLE;
DROP TABLE POLICY;
DROP TABLE REPORT;
DROP TABLE PREFERENCE;
DROP TABLE SERVER_PREFERENCE;
DROP TABLE FAMILY_SELECTION;
DROP TABLE INDIVIDUAL_PLUGIN_SELECTION;
DROP TABLE REPORT_HOST;
DROP TABLE REPORT_ITEM;
DROP TABLE HOST_PROPERTIES;
DROP TABLE REPORT_ITEM_ATTRIBUTE;
DROP TABLE PLUGINS_PREFERENCE;

