INSERT INTO USERS (USER_ID,PASSWORD,FIRST_NAME,MIDDLE_NAME,LAST_NAME,EMAIL,PHONE,ROLE) 
VALUES ('Ron','12345','Ronald','','Ingram','rei0036@gmail.com','2021234567','admin');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('','NessusClientData_v2');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('root','Policy');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('Policy','policyName');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('Policy','Preferences');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('Preferences','ServerPreferences');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('ServerPreferences','preference');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('Preferences','PluginsPreferences');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('PluginsPreferences','item');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('Policy','FamilySelection');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('FamilySelection','FamilyItem');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('Policy','IndividualPluginSelection');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('IndividualPluginSelection','PluginItem');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('root','Report');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('Report','ReportHost');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('ReportHost','HostProperties');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('ReportHost','ReportItem');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('ReportItem','Item');

INSERT INTO NESSUS_STRUCTURE (PARENT_NAME,NAME) 
VALUES ('ReportItem','Attribute');

INSERT INTO ORGANIZATION (ORG_NAME,DESCRIPTION) 
VALUES ('NSD','Network Security Deployment');

INSERT INTO ORGANIZATION (ORG_NAME,DESCRIPTION) 
VALUES ('ISMD', 'Information Security Management Department');

INSERT INTO ORGANIZATION (ORG_NAME,DESCRIPTION) 
VALUES ('SCDAS', 'Supervisory Control and Data Acquisition System');

INSERT INTO ORGANIZATION (ORG_NAME,DESCRIPTION) 
VALUES ('HSCNS', 'High School Computer Network System');

INSERT INTO ORGANIZATION (ORG_NAME,DESCRIPTION) 
VALUES ('NSD','Network Security Deployment');
